### ISSUE TITLE
Status displays all informations as N/A if built and ran through `podman compose up -d`

### ISSUE THREAD

**Issue by lunaposs** [dani3l0/Status#16]
in case, quick uname:` Linux inanna 6.12.21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.21-1 (2025-03-30) x86_64 GNU/Linux`

I have followed the procedure for containerized Status with Docker, except through Podman, so I simply replaced the last line with `podman compose up -d`, which is thin wrapper around an external compose provider such as docker-compose, and local Podman socket is used in place of Docker socket.

Once the container is up, I can access the status page. However, it looks like this:

 
![Image](https://github.com/user-attachments/assets/a25d5499-2bdb-4785-b30b-b42b42fffdff)

A quick `podman unshare` and finding the mount has revealed that the `host_root` directory have both empty directories and files:

host_root/
├─ etc/
│  ├─ hostname (empty)
│  ├─ os-release (empty)
├─ proc/

Not sure if this bit is relevant, but composing fails beforehand when attempting to mount `/run/media`.

**Comment by lunaposs** [comment]
Update: After asking around and testing, the culprit seems to be in the `docker-compose.yml`, specifically line 10, which will cause non-logged error, preventing Status from supplying informations about the host.

I also would kindly recommend to:
- Remove `"/run/media:/run/media:ro"` since it causes error during composing
- Either remove `"/proc/mounts:/host_root/proc/mounts"` or apply `ro` strictly to both `/proc` and `/proc/mounts`
- Exposing `/home` is a bad idea, there should be other equally reliable ways to gather information about storages and storage use without mounting sensitive directories.

**Comment by lunaposs** [comment]
Many thanks to Matrix user going by tblFlip on suggested changes and improvements as well:

`docker-compose.yml`:
```
version: "2"
services:
  app:
    container_name: status_app
    build: .
    volumes:
      - "/etc/os-release:/host_root/etc/os-release:ro"
      - "/etc/hostname:/host_root/etc/hostname:ro"
      - "/proc:/host_root/proc:ro"
    ports:
      - 9090:9090/tcp
```

`Dockerfile`:
```
FROM python:3.11-alpine
WORKDIR /app
COPY . .
ENV STATUS_CUSTOM_ROOT_PATH=/host_root
RUN pip install --no-cache-dir --disable-pip-version-check -r requirements.txt
USER nobody:nogroup
CMD ["python", "status.py", "--no-config"]
EXPOSE 9090
```

These eliminate the security issues and errors completely. :3
